### ISSUE TITLE
Add contribution guide

### ISSUE THREAD

**Issue by mazipan** [mazipan/milligram-admin-dashboard-template#1]
I need contribution guide in this repo.
You can see the sample contribution guide from this pull request
https://github.com/mazipan/vue-currency-filter/pull/5/files

Thanks for your help 🎉🎉🎉

**Comment by UchihaCFC** [comment]
@mazipan can I do this? 

I'm interested too in contribute on the future in admin-template (:

**Comment by mazipan** [comment]
Sure

**Comment by UchihaCFC** [comment]
Has sent you a [pull request](https://github.com/mazipan/milligram-admin-dashboard-template/pull/2) for this. 

If you want to change anything you can tell me ;)
